#!/usr/bin/env bash
set -euo pipefail

GEM5_DIR="${GEM5_DIR:-${HOME}/gem5}"
BRANCH="fix/thermal-intermediate-node-init"
GERRIT_URL="https://gem5-review.googlesource.com/gem5"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
die()   { echo -e "${RED}[✗]${NC} $*"; exit 1; }

if [ ! -d "$GEM5_DIR" ]; then
    die "gem5 directory not found: $GEM5_DIR"
fi

cd "$GEM5_DIR"

# ── Step 1: Gerrit remote ──────────────────────────────────────────────────────
info "Step 1/6: Setting up Gerrit remote"
if git remote get-url gerrit &>/dev/null; then
    warn "Remote 'gerrit' already exists, skipping"
else
    git remote add gerrit "$GERRIT_URL"
    info "Remote 'gerrit' added → $GERRIT_URL"
fi

# ── Step 2: commit-msg hook ────────────────────────────────────────────────────
info "Step 2/6: Installing Gerrit commit-msg hook"
curl -sLo .git/hooks/commit-msg \
    https://gem5-review.googlesource.com/tools/hooks/commit-msg
chmod +x .git/hooks/commit-msg
info "Hook installed at .git/hooks/commit-msg"

# ── Step 3: Fetch develop ──────────────────────────────────────────────────────
# Fetch from GitHub mirror (public, no auth needed); push will still go to Gerrit
info "Step 3/6: Fetching gem5 develop branch from GitHub mirror"
git fetch origin develop
info "Fetched origin/develop"

# ── Step 4: Create patch branch ───────────────────────────────────────────────
info "Step 4/6: Creating branch '$BRANCH' from origin/develop"
if git show-ref --verify --quiet refs/heads/"$BRANCH"; then
    warn "Branch '$BRANCH' already exists — checking it out"
    git checkout "$BRANCH"
else
    git checkout -b "$BRANCH" origin/develop
fi

# ── Step 5: Apply fix ─────────────────────────────────────────────────────────
info "Step 5/6: Applying thermal model fix"

# Check if already applied
if grep -q "Initialize intermediate nodes" src/sim/power/thermal_model.cc; then
    warn "Fix already present on this branch, skipping apply"
else
    # Generate diff from origin/stable where the change was made
    git diff origin/stable -- src/sim/power/thermal_model.cc | git apply
    info "Patch applied to src/sim/power/thermal_model.cc"
fi

git add src/sim/power/thermal_model.cc

git commit -m "sim/power: initialize intermediate thermal nodes to ambient temp

ThermalModel::startup() initializes only ThermalDomain and
ThermalReference nodes. Intermediate structural nodes (e.g. node_pkg
in a 2-node Cauer RC network) retain the 0 K (absolute zero) default
from ThermalNode's constructor. ThermalCapacitor::getEquation() uses
n->temp as T_prev in the Backward Euler discretization; a 0 K
intermediate node acts as an absolute-zero heat sink in the first
solver step, causing physically impossible junction cooling.

Observed symptom: die temperature drops 25 C -> 12.34 C under ~3 W
positive CPU power in a 2-node Cauer RC network, with the die
temperature falling below ambient instead of rising toward steady-state.

Fix: after building eq_nodes in startup(), initialize any node whose
temperature is below 1 K (i.e. the uninitialized 0 K constructor
default) to the first ThermalReference temperature (ambient). Domain
nodes are already initialized before eq_nodes is built and are
unaffected by this check.

Independent verification: a Backward Euler Python solver with identical
Cauer 2-node RC parameters reproduces the anomalous 12.29 C result
(gem5 observed: 12.34 C, deviation: 0.05 C). With correct 298 K
initialization the die temperature reaches 25.03 C as physics requires.

Reproduction dataset, verification script, and full analysis:
https://github.com/rtester1111-tech/arm-thermal-research"

info "Commit created (Change-Id generated by hook)"
git log --oneline -1

# ── Step 6: Gerrit auth + push ─────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
warn "Step 6/6: Gerrit authentication required before push"
echo ""
echo "  1. Open in browser:"
echo "     https://gem5-review.googlesource.com"
echo ""
echo "  2. Sign in (top-right) with your Google account"
echo ""
echo "  3. Click your avatar → Settings → HTTP Credentials"
echo "     → Generate Password"
echo ""
echo "  4. Copy and run the 'git config' commands shown on that page"
echo "     (they look like: git config --global http.cookiefile ...)"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
read -rp "Press ENTER after completing Gerrit authentication to push... "

info "Pushing to Gerrit refs/for/develop"
git push gerrit HEAD:refs/for/develop

echo ""
info "Done! Copy the Gerrit URL printed above and add it as a comment"
info "on your GitHub issue to link the bug report with the code review."
